### ISSUE TITLE
How to write my own main loop?

### ISSUE THREAD

**Issue by fkanehiro** [unitreerobotics/aliengo_sdk#1]
Hi,

Examples in this repository are calling `control.loop.Start()` and execution of `main()` is blocked by this function.
I want to integrate the control loop into my own main loop.
Is it possible?

**Comment by TrivasZhang** [comment]
Because main() will exit if not block with while(). 
new method please check:
https://github.com/unitreerobotics/unitree_legged_sdk/tree/master/examples

**Comment by fkanehiro** [comment]
Thank you for the new method.
I understood that I can write my own `main()` like this:

```
int main()
{
    ...
    while(1){
        ...
        UDPSend(custom);
        ...
        UDPRecv(custom);
        ...
        RobotControl(custom);
        ...
    }
    ...
}
```

Is my understanding correct?

**Comment by TrivasZhang** [comment]
Sure. But multithread will not block each other.

**Comment by fkanehiro** [comment]
Thanks!
